files:
  - path: Patbox's Mods/ArmorStandEditor-en_us.json
    source: https://github.com/Patbox/ArmorStandEditor/blob/1.19.3/src/main/resources/data/armor_stand_editor/lang/en_us.json
  - path: Patbox's Mods/BiomeTechnologies-en_us.json
    source: https://github.com/Patbox/BiomeTechnologies/blob/1.19.3/src/main/resources/data/biometech/lang/en_us.json
  - path: Patbox's Mods/Brewery-en_us.json
    source: https://github.com/Patbox/brewery/blob/1.19.3/src/main/resources/data/brewery/lang/en_us.json
  - path: Patbox's Mods/EntityViewDistance-en_us.json
    source: https://github.com/Patbox/EntityViewDistance/blob/1.19.3/src/main/resources/assets/entityviewdistance/lang/en_us.json
  - path: Patbox's Mods/GOML-ReServed-en_us.json
    source: https://github.com/Patbox/get-off-my-lawn-reserved/blob/1.19.3/src/main/resources/data/goml/lang/en_us.json
  - path: Patbox's Mods/Holograms-en_us.json
    source: https://github.com/Patbox/Holograms/blob/1.19.3/src/main/resources/data/holograms/lang/en_us.json
  - path: Patbox's Mods/Polydex-en_us.json
    source: https://github.com/Patbox/polydex/blob/1.19.3/src/main/resources/data/polydex/lang/en_us.json
  - path: Patbox's Mods/TaterCart-en_us.json
    source: https://github.com/Patbox/TaterCart/blob/1.19/src/main/resources/data/tatercart/lang/en_us.json
  - path: Patbox's Mods/UniversalGraves-en_us.json
    source: https://github.com/Patbox/UniversalGraves/blob/1.19.3/src/main/resources/data/universal_graves/lang/en_us.json
  - path: Patbox's Mods/UniversalShops-en_us.json
    source: https://github.com/Patbox/UniversalShops/blob/1.19.3/src/main/resources/data/universal_shops/lang/en_us.json
  - path: Patbox's Mods/PolymerPorts/Trinkets-en_us.json
    source: https://github.com/PolymerPorts/trinkets/blob/main/src/main/resources/data/trinkets/lang/en_us.json
  - path: Patbox's Mods/PolymerPorts/FabricWaystones-en_us.json
    source: https://github.com/PolymerPorts/FabricWaystones/blob/master/src/main/resources/data/polyportwaystones/lang/en_us.json
  - path: Patbox's Mods/PolymerPorts/Illager-Expansion-Rematch-en_us.json
    source: https://github.com/PolymerPorts/Illager-Expansion-Rematch/blob/main/src/main/resources/data/illagerexp/lang/en_us.json
  - path: Patbox's Mods/PolymerPorts/CC-Restitched-en_us.json
    source: https://github.com/PolymerPorts/cc-restitched/blob/mc-1.19.x/polymer/src/main/resources/data/computercraft/lang/en_us.json
